-- Sync brows content with ESTEQO WEBSITE CONTENT (1).docx.
-- Safe to re-run.

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (1, 1, 'brow-shape', 'Brow Shape & Brow Mapping', 'Your eyebrows are either an asset or a liability. We map your face, remove only what needs to go, and leave you looking sharper.', '["Crisp, defined brows tailored to your face", "No pain, no swelling, no downtime", "Results last 3–4 weeks"]', '[]', 'Brows look undefined or messy • One brow higher than the other • Over-plucked and sparse • Preparing for permanent makeup', 20, NULL, '/uploads/brows/brow_shape.jpg', 1, 1, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (3, 1, 'hd-brows', 'HD Brows Tint', 'Faded, sparse or undefined brows make you look tired. Custom tinting, precision mapping and professional shaping give your brows colour, definition and balance.', '["Sculpted, tinted brows that look thick and defined", "Colour stays 2–3 weeks, shape holds 4 weeks", "Same-day results, zero downtime"]', '[]', 'Brows look faded or washed out • Over-plucked or sparse areas • Uneven density or asymmetrical • Want defined, coloured brows without daily makeup', 30, NULL, '/uploads/brows/hd_brows.jpg', 2, 1, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (4, 1, 'brow-lamination', 'Brow Lamination', 'Messy, downward-growing brows make you look tired and sparse brows disappear entirely. Lamination fixes both — we smooth, lift and set your brows in place for fuller definition without daily brushing.', '["Lifted, smooth, fuller-looking brows that stay set", "No daily brushing needed", "Shape holds 4–6 weeks, zero downtime"]', '[]', 'Brows grow downward or look unruly • Want a fuller appearance without daily grooming • Sparse, thin, or directionally challenging hair • Need a polished, lifted brow look', 40, NULL, '/uploads/brows/brow_lamination.jpg', 3, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (5, 1, 'microblading', 'Microblading / Nanoblading', 'Over-plucked, sparse or thin brows mean you draw them on every morning. Nanoblading creates hair-like strokes that look completely natural — you wake up with brows already done.', '["Full, defined, natural-looking brows for 6 months", "Two visits: the session plus a refinement at 4–12 weeks", "Healing takes 3–4 weeks, with light flaking normal"]', '[]', 'Over-plucked or sparse brows • Tired of drawing brows daily • Want natural-looking enhancement • Seeking a 6-month commitment, not permanent', 60, NULL, '/uploads/brows/microblading.jpg', 4, 1, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (6, 1, 'ombre-brow', 'Ombre Brow', 'Filling in your brows every morning wastes time you don''t have. Ombre Brows end that for up to 18 months with soft, powder-shaded colour that never smudges or wipes off.', '["Defined brows that hold colour for up to 18 months", "Free perfecting session at 4–12 weeks", "No daily routine, no downtime"]', '[]', 'Oily or combination skin where regular brow tattoos fade fast • Sparse, uneven, or over-plucked brows needing real density • Anyone done with pencil and powder every morning • Old PMU or faded pigment that needs correcting • People who want polished brows with zero upkeep', 90, NULL, '/uploads/brows/ombre_brow.jpg', 5, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (7, 1, 'hybrid-brow', 'Hybrid / Combination Brow', 'Microblading alone fades fast and ombre alone can look flat. Hybrid Brows combine both — hair strokes up front and soft shading through the tail, without the trade-offs.', '["Natural, dense brows that hold for up to 18 months", "Retouch session at 4–12 weeks", "No sketchy edges, no flat shading"]', '[]', 'Oily skin or leftover pigment from old brow work • Sparse or uneven brows needing more density • Anyone wanting strokes plus soft definition • People who want fuller brows without daily filling in • Clients ready to commit to one shape, one colour', 90, NULL, '/uploads/brows/hybrid_brow.jpg', 6, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (8, 1, 'brow-tattoo-removal', 'Eyebrow Tattoo & PMU Removal', 'Old microblading or PMU doesn''t just disappear on its own. Saline removal draws unwanted pigment out gradually, so a bad brow can be corrected without waiting years for it to fade.', '["Pigment fades progressively, session by session", "Sessions spaced 4 weeks apart", "No laser required"]', '[]', 'Outdated or poorly healed eyebrow tattoos • Uneven or mismatched previous microblading • Brows with unwanted colour shifts or heavy pigment saturation • Anyone wanting a pigment reset before new PMU • Correction cases needing shape or tone fixed', 60, NULL, '/uploads/brows/tattoo-removal.jpg', 7, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (231, 1, 'mole-creation', 'Mole Creation', 'Drawing on a fake mole every morning never looks natural. PMU mole creation deposits pigment in one precise spot, so you get a permanent mark that reads as real.', '["A single, natural-looking mole placed exactly where you want it", "One quick session", "Touch up only if needed"]', '[]', 'Anyone drawing on a fake beauty mark for years • People wanting a signature facial feature added • Clients missing a mole from a past scar or removal • Those who want subtle, natural-looking placement • Anyone tired of makeup that smudges by noon', NULL, NULL, NULL, 8, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (232, 1, 'scalp-micropigmentation', 'Scalp Micropigmentation', 'A thinning patch on your scalp doesn''t fix itself, and hats can only hide so much. Scalp micropigmentation deposits pigment dots that mimic real hair follicles, filling in patches for a fuller, denser look.', '["A full, natural-looking scalp with density restored", "Results last years with upkeep", "No surgery, no downtime"]', '[]', 'Thinning patches from alopecia, stress, or genetics • Scars from past hair transplants or injuries • Anyone tired of concealer powder that washes out • People wanting denser hair without a transplant • Those who shave their head and want a defined hairline', NULL, NULL, NULL, 9, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

INSERT INTO `services` (`id`,`category_id`,`slug`,`name`,`summary`,`bullets`,`what_to_expect`,`ideal_for`,`duration_minutes`,`price`,`image`,`sort_order`,`is_featured`,`is_active`,`description`) VALUES (233, 1, 'lip-blush', 'Lip Blush', 'Lipstick smudges, fades and needs reapplying all day. Lip Blush deposits soft pigment into your lips, adding natural colour and definition that stays put from morning to night.', '["Natural-looking colour and definition for one to three years", "Perfecting session at 4–8 weeks", "No daily lipstick, no smudging"]', '[]', 'Pale or uneven lip tone needing natural colour • Thin lips wanting a more defined shape • Anyone tired of reapplying lipstick throughout the day • People wanting a soft, your-lips-but-better tint • Clients correcting faded or patchy past lip tattoos', NULL, NULL, NULL, 10, 0, 1, NULL)
ON DUPLICATE KEY UPDATE `slug`=VALUES(`slug`),`name`=VALUES(`name`),`summary`=VALUES(`summary`),`bullets`=VALUES(`bullets`),`ideal_for`=VALUES(`ideal_for`),`duration_minutes`=VALUES(`duration_minutes`),`image`=VALUES(`image`),`sort_order`=VALUES(`sort_order`),`is_featured`=VALUES(`is_featured`),`is_active`=VALUES(`is_active`);

UPDATE `services` SET `is_active` = 0 WHERE `slug` = 'brow-tint';
